packages:
  - apps/*
  - packages/*
  - packages/interactions/*

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - puppeteer
  - rs-module-lexer
  - unrs-resolver

patchedDependencies:
  '@wc-toolkit/storybook-helpers@10.2.1': patches/@wc-toolkit__storybook-helpers@10.2.1.patch
