import { readdirSync, readFileSync, existsSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { defineConfig } from 'tsup';

import pkgJson from './package.json' with { type: 'json' };
import { InlineCSSPlugin } from '../../tools/build/inline-css-plugin';

import type { Options } from 'tsup';

const here = fileURLToPath(new URL('.', import.meta.url));
const workspaceRoot = resolve(here, '../..');

/**
 * tsconfig `paths` resolving every `@qti-components/*` specifier to the sibling package's
 * built declarations. Used by the declaration build only.
 *
 * The JS bundle inlines these packages (they are devDependencies, deliberately not
 * shipped), but `dts: { resolve: true }` only inlines types behind BARE specifiers — it
 * leaves deep subpaths like `@qti-components/interactions-core/elements/qti-simple-choice`
 * external. src imports those subpaths ~20 times, so the published .d.ts imported packages
 * no consumer ever installs: the runtime worked while the types were unresolvable, and
 * consumers had to install the devDependencies by hand to type-check at all.
 *
 * Giving rollup-plugin-dts declaration files to follow makes the emitted .d.ts
 * self-contained, matching the JS. Nothing but real runtime dependencies (`lit`,
 * `@heximal/templates`) is left external.
 *
 * Generated by scanning the workspace rather than hand-listed: the package name does not
 * imply its directory (`@qti-components/elements` lives in `packages/qti-elements`,
 * `@qti-components/choice-interaction` in `packages/interactions/choice-interaction`), and
 * a static list would drift the moment a package is added or moved.
 *
 * Requires the sibling packages to be built first, which the topological workspace build
 * already guarantees.
 */
function workspaceTypePaths(): Record<string, string[]> {
  const paths: Record<string, string[]> = {};
  const roots = [join(workspaceRoot, 'packages'), join(workspaceRoot, 'packages/interactions')];

  for (const root of roots) {
    if (!existsSync(root)) continue;
    for (const dir of readdirSync(root, { withFileTypes: true })) {
      if (!dir.isDirectory()) continue;
      const manifest = join(root, dir.name, 'package.json');
      if (!existsSync(manifest)) continue;

      const { name } = JSON.parse(readFileSync(manifest, 'utf8')) as { name?: string };
      if (!name?.startsWith('@qti-components/')) continue;

      const dist = relative(here, join(root, dir.name, 'dist'))
        .split('\\')
        .join('/');

      /*
       * Point at each package's built .d.ts, not its source. rollup-plugin-dts consumes
       * declaration files natively; handed .ts source for a barrel it re-exports types
       * from, it keeps the module external and names it by directory — emitting an
       * unresolvable `import * as src from 'src'`.
       *
       * The candidates mirror each package's own `exports` map, in the order TypeScript
       * should try them: a direct file, then a directory index.
       */
      paths[name] = [`${dist}/index.d.ts`];
      paths[`${name}/*`] = [`${dist}/*.d.ts`, `${dist}/*/index.d.ts`, `${dist}/*`];
    }
  }
  return paths;
}

const dependencies = Object.keys(pkgJson.dependencies || {});

/**
 * Lit must be a singleton, so the npm build imports it rather than inlining it.
 *
 * `noExternal: dependencies` used to bundle lit into dist/ while package.json ALSO
 * declared it a dependency — so a consumer got the bundled copy *and* installed one, and
 * any consumer with its own Lit components ended up running two. Two copies mean two
 * `ReactiveElement` base classes (so `instanceof` fails across them), two `@lit/context`
 * registries, and lit's own "Multiple versions of Lit loaded" warning, which fires on the
 * COUNT of registered instances — matching versions does not help.
 *
 * Subpaths matter: `lit/decorators.js` and `@lit/context` have to stay external too, so
 * this is matched by pattern rather than by bare package name.
 *
 * The two CDN builds below are unaffected — they set their own `noExternal: [/(.*)/]`
 * because a CDN bundle genuinely has to be self-contained.
 */
const litExternal = [/^lit($|\/)/, /^lit-html($|\/)/, /^lit-element($|\/)/, /^@lit\//];
const bundledDependencies = dependencies.filter(name => !/^(lit|lit-html|lit-element|@lit)($|[/-])/.test(name));

export default defineConfig(async () => {
  const npmOptions: Options = {
    clean: false, // handled by our npm script
    outDir: 'dist',
    format: 'esm',
    entry: ['./src/**/*.ts'],
    external: litExternal,
    noExternal: bundledDependencies,
    splitting: true,
    esbuildPlugins: [InlineCSSPlugin],
    sourcemap: true,
    dts: {
      resolve: true,
      compilerOptions: { paths: workspaceTypePaths() }
    }
  };

  // CDN build (ESM, bundled deps)
  const cdnEsmOptions: Options = {
    clean: false,
    outDir: 'cdn',
    format: 'esm',
    entry: {
      index: './src/index.ts'
    },
    external: undefined,
    noExternal: [/(.*)/],
    splitting: false,
    esbuildPlugins: [InlineCSSPlugin],
    sourcemap: false,
    minify: true,
    dts: false
  };

  // CDN build (UMD/Global for JSDOM and browser environments)
  const cdnUmdOptions: Options = {
    clean: false,
    outDir: 'cdn',
    format: 'iife',
    entry: {
      index: './src/index.ts'
    },
    globalName: 'QtiComponents',
    target: 'es5',
    external: undefined,
    noExternal: [/(.*)/],
    splitting: false,
    esbuildPlugins: [InlineCSSPlugin],
    sourcemap: false,
    minify: true,
    dts: false
  };

  return [npmOptions, cdnEsmOptions, cdnUmdOptions];
});
