/**
 * Regenerates `reserved.json` — the set of `qti-` names 1EdTech owns.
 *
 * Run by hand, not in CI: it needs the network, and the answer only changes when 1EdTech
 * publishes. CI reads the committed `reserved.json` instead.
 *
 *   node tools/qti-vocabulary/generate.mjs
 *
 * Two sources, because the vocabulary is split across two of them:
 *
 *   elements    imsqti_asiv3p0_v1p0.xsd — the ASI schema, which is versioned and normative.
 *   vocabulary  the Shared Vocabulary page. NOT in the schema. The implementation guide
 *               (§2.2.2) says it is "maintained outside of the QTI specification (schema)",
 *               which is the whole reason this check exists: 1EdTech can add a name to it
 *               without a version bump, so a `qti-` name we invent today can collide
 *               tomorrow with no signal to us.
 *
 * The vocabulary page is scraped, so it carries some noise — HTML anchor ids for duplicate
 * headings pick up a `-N` suffix, and prose writes families as `qti-layout-offset-*`. Tokens
 * ending in `-` are dropped; the rest are kept as-is. Erring towards permitting a few names
 * that are not real beats failing the build on a scrape artifact.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const XSD = 'https://purl.imsglobal.org/spec/qti/v3p0/schema/xsd/imsqti_asiv3p0_v1p0.xsd';
const VOCAB = 'https://www.imsglobal.org/spec/qti/v3p0/vocab';

const fetchText = async url => {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return res.text();
};

const sorted = set => [...set].sort();

const main = async () => {
  process.stdout.write(`Fetching ${XSD}\n`);
  const xsd = await fetchText(XSD);
  const elements = new Set([...xsd.matchAll(/<xs:element[^>]*name="(qti-[^"]+)"/g)].map(m => m[1]));

  process.stdout.write(`Fetching ${VOCAB}\n`);
  const vocabHtml = await fetchText(VOCAB);
  const vocabulary = new Set(
    [...vocabHtml.matchAll(/\bqti-[a-z0-9]+(?:-[a-z0-9]+)*/g)].map(m => m[0]).filter(n => !n.endsWith('-'))
  );

  const out = {
    $comment: 'GENERATED by tools/qti-vocabulary/generate.mjs. Do not hand-edit.',
    generatedAt: new Date().toISOString().slice(0, 10),
    sources: { elements: XSD, vocabulary: VOCAB },
    elements: sorted(elements),
    vocabulary: sorted(vocabulary)
  };

  const target = join(dirname(fileURLToPath(import.meta.url)), 'reserved.json');
  writeFileSync(target, `${JSON.stringify(out, null, 2)}\n`);
  process.stdout.write(`Wrote ${target}: ${out.elements.length} elements, ${out.vocabulary.length} vocabulary names\n`);
};

main().catch(err => {
  process.stderr.write(`${err.message}\n`);
  process.exit(1);
});
