// Type declarations for @qti-components/elements
export declare const QtiAssessmentItem: any;
export declare const QtiAssessmentItemRef: any;
export declare const QtiAssessmentSection: any;
export declare const QtiAssessmentStimulusRef: any;
export declare const QtiAssessmentStimulusRefConnectedEvent: any;
export declare const QtiCompanionMaterialsInfo: any;
export declare const QtiContentBody: any;
export declare const QtiCustomOperator: any;
export declare const QtiFeedback: any;
export declare const QtiFeedbackBlock: any;
export declare const QtiFeedbackInline: any;
export declare const QtiItemBody: any;
export declare const QtiModalFeedback: any;
export declare const QtiPrompt: any;
export declare const QtiRubricBlock: any;
export declare const QtiStylesheet: any;
