name: Run storybook test for conformance branche

on:
  push:
    branches:
      - conformance  # Trigger on push to the dev branch, adjust as needed

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Git configuration
        run: |
          git config --global user.email "patrick.deklein@cito.nl"
          git config --global user.name "patrickdeklein"

      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify the Node.js version
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci
  
      - name: Build
        run: npm run build
      - name: Install playwright
        run: npx playwright install  --with-deps
      - name: Test build
        run: npm run test
      - name: Test Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: npm run chromatic


