name: Deploy Storybook

on:
  # Allow manual runs
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch, tag, or SHA) to deploy"
        required: false
        default: "main"
        type: string
  # Allow other workflows to call this
  workflow_call:
    inputs:
      ref:
        description: "Git ref (branch, tag, or SHA) to deploy"
        required: false
        type: string
        default: ""
    outputs:
      page_url:
        description: "GitHub Pages URL"
        value: ${{ jobs.deploy.outputs.page_url }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Storybook to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Resolve ref
        id: ref
        run: |
          # Prefer input from workflow_call / workflow_dispatch; fall back to current SHA
          if [ -n "${{ inputs.ref }}" ]; then
            echo "value=${{ inputs.ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.value }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Summary
        run: |
          echo "✅ Deployed Storybook to: ${{ steps.deployment.outputs.page_url }}"